version: '3'
services:
  release:
    build:
      context: .
      dockerfile: Dockerfile.release
  master:
    build:
      context: .
      dockerfile: Dockerfile.master
  linked:
    build:
      context: .
      dockerfile: Dockerfile.linked
  josh:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCC_ARGS: "-D none -Iuser:joshmoore"
  all:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCC_ARGS: "-D all"
