version: '3'
services:
  release:
    build:
      context: .
      dockerfile: Dockerfile.release
    entrypoint: /src/test.sh
  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    entrypoint: /src/test.sh
  master-fix:
    build:
      context: .
      dockerfile: Dockerfile.master
      args:
        SPTX_FORMAT: "https://github.com/joshmoore/sptx-format/archive/setup-packages.zip"
    entrypoint: /src/test.sh
  linked:
    build:
      context: .
      dockerfile: Dockerfile.linked
      args:
        SPTX_FORMAT: "https://github.com/joshmoore/sptx-format/archive/setup-packages.zip"
    entrypoint: /src/test.sh
  josh:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCC_ARGS: "-D none -Iuser:joshmoore"
    entrypoint: /src/test.sh
  all:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCC_ARGS: "-D all"
    entrypoint: /src/test.sh
