FROM continuumio/miniconda3
RUN useradd -m starfish
USER starfish

# Set up the initial conda environment
RUN conda create -n env python=3.6 pip
RUN echo "source activate env" >> ~/.bashrc
ENV PATH /home/starfish/.conda/envs/env/bin:$PATH
env MPLBACKEND Agg

# Setup test
ADD --chown=starfish https://raw.githubusercontent.com/spacetx/starfish/0.0.14/examples/get_iss_data.py /src/starfish/examples/get_iss_data.py
WORKDIR /src

# Install from pypi
RUN pip install starfish

ENTRYPOINT ["pytest"]
